Readme fixes
Signiant/umpire pull request #5
Opened 2018-10-03 20:06 UTC by mbuttler

2018-10-03 20:11 UTC, haggaret approved these changes

2018-10-04 14:05 UTC, miketypeguy requested changes
Take a peak at some of my comments and let me know why I'm wrong 👍

2018-10-04 14:05 UTC, miketypeguy commented on README.md
> +# Umpire Dependency Manager
I mean the name is Umpire and it is a dependency manager but I wouldn't say that has to be part of the name.

2018-10-04 14:05 UTC, miketypeguy commented on README.md
> -Don't have pip? Get it [here.](https://pypi.python.org/pypi/pip)
I don't see anything wrong with mentioning how to get pip

2018-10-04 14:05 UTC, miketypeguy commented on README.md
> +Umpire reads a JSON file to retrieve, cache, and link files to their appropriate destination from an Amazon S3 backed repository of compressed packages.
The way this was switched around makes sense and still relays the pertinent information.

2018-10-04 14:05 UTC, miketypeguy commented on README.md
> +Want to help out?
I think helping out is Awesome still.

2018-10-04 14:56 UTC, mbuttler commented on README.md
> -Don't have pip? Get it [here.](https://pypi.python.org/pypi/pip)
Agreed. Take thyself a look.

2018-10-04 15:09 UTC, miketypeguy approved these changes
Looks good

2018-10-04 15:09 UTC, merged